Option Strict On
Option Explicit On
Imports System.IO
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = True
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.PhanMemBanHang.frmMain
        End Sub

        Private Sub MyApplication_Shutdown(sender As Object, e As EventArgs) Handles Me.Shutdown
            mdlGlobals.BatTatCan()

            ' Xóa file tạm
            mdlGlobals.XoaFileTam()

            ' kiểm tra xem máy tính này có được phép sử dụng chức năng backup hay không?
            If My.Settings.KhongDuocPhepBackup = False Then Exit Sub

            If My.Settings.SaoLuuKhiTatChuongTrinh Then
                mdlGlobals.BackupDatabase()
            End If
        End Sub

        Private Sub MyApplication_Startup(sender As Object, e As ApplicationServices.StartupEventArgs) Handles Me.Startup
            ' kiểm tra xem máy tính này có được phép sử dụng chức năng backup hay không?
            If My.Settings.KhongDuocPhepBackup = False Then Exit Sub
            ' tự động xoá file backup
            Try
                Dim soNgay As Integer = 0
                If My.Settings.CoBak10Ngay Then
                    soNgay = 10
                ElseIf My.Settings.CoBak30Ngay Then
                    soNgay = 30
                End If
                If soNgay <> 0 Then
                    mdlGlobals.XoaBakFile(Now.AddDays(-soNgay), My.Settings.DuongDanFileBackup)
                End If
            Catch ex As Exception

            End Try

            ' Tự động backup khi khởi động
            If My.Settings.SaoLuuKhiDangNhap Then
                mdlGlobals.BackupDatabase()
            End If

            ' Tự động backup hàng tuần
            If My.Settings.SaoLuuHangTuan Then
                If My.Settings.SaoLuuVaoThuMay = 0 Then ' Thứ 2
                    If Now.DayOfWeek = DayOfWeek.Monday Then
                        mdlGlobals.BackupDatabase()
                    End If
                ElseIf My.Settings.SaoLuuVaoThuMay = 1 Then ' Thứ 3
                    If Now.DayOfWeek = DayOfWeek.Tuesday Then
                        mdlGlobals.BackupDatabase()
                    End If
                ElseIf My.Settings.SaoLuuVaoThuMay = 2 Then ' Thứ 4
                    If Now.DayOfWeek = DayOfWeek.Wednesday Then
                        mdlGlobals.BackupDatabase()
                    End If
                ElseIf My.Settings.SaoLuuVaoThuMay = 3 Then ' Thứ 5
                    If Now.DayOfWeek = DayOfWeek.Thursday Then
                        mdlGlobals.BackupDatabase()
                    End If
                ElseIf My.Settings.SaoLuuVaoThuMay = 4 Then ' Thứ 6
                    If Now.DayOfWeek = DayOfWeek.Friday Then
                        mdlGlobals.BackupDatabase()
                    End If
                ElseIf My.Settings.SaoLuuVaoThuMay = 5 Then ' Thứ 7
                    If Now.DayOfWeek = DayOfWeek.Saturday Then
                        mdlGlobals.BackupDatabase()
                    End If
                Else ' Chủ nhật
                    If Now.DayOfWeek = DayOfWeek.Sunday Then
                        mdlGlobals.BackupDatabase()
                    End If
                End If
            End If
        End Sub

        Private Sub MyApplication_UnhandledException(sender As Object, e As UnhandledExceptionEventArgs) Handles Me.UnhandledException
            ' Ghi log 
            Dim strAppData As String = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\PhanMemBanHang"
            If Not Directory.Exists(strAppData) Then
                Directory.CreateDirectory(strAppData)
            End If
            Dim strFileName = strAppData + "\Log_" + Now.ToString("dd_MM_yy_HH_mm_ss") + ".txt"
            File.WriteAllText(strFileName, e.Exception.Message + vbNewLine + "---" + vbNewLine + e.Exception.StackTrace + vbNewLine + "---INNER---" + vbNewLine + e.Exception.InnerException.StackTrace)
        End Sub
    End Class
End Namespace
