'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DuongDanAnh() As String
            Get
                Return CType(Me("DuongDanAnh"),String)
            End Get
            Set
                Me("DuongDanAnh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property SoChuSoKhongPhieu() As Integer
            Get
                Return CType(Me("SoChuSoKhongPhieu"),Integer)
            End Get
            Set
                Me("SoChuSoKhongPhieu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property SoDongTimKiem() As Integer
            Get
                Return CType(Me("SoDongTimKiem"),Integer)
            End Get
            Set
                Me("SoDongTimKiem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property ThoiGianTimKiemCham() As Integer
            Get
                Return CType(Me("ThoiGianTimKiemCham"),Integer)
            End Get
            Set
                Me("ThoiGianTimKiemCham") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property KieuHoaDon() As Integer
            Get
                Return CType(Me("KieuHoaDon"),Integer)
            End Get
            Set
                Me("KieuHoaDon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property KieuPhieuXuat() As Integer
            Get
                Return CType(Me("KieuPhieuXuat"),Integer)
            End Get
            Set
                Me("KieuPhieuXuat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property KieuPhieuNhap() As Integer
            Get
                Return CType(Me("KieuPhieuNhap"),Integer)
            End Get
            Set
                Me("KieuPhieuNhap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MacDinhTimKiemSanPham() As Integer
            Get
                Return CType(Me("MacDinhTimKiemSanPham"),Integer)
            End Get
            Set
                Me("MacDinhTimKiemSanPham") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property SoDongTimKiemSanPham() As Integer
            Get
                Return CType(Me("SoDongTimKiemSanPham"),Integer)
            End Get
            Set
                Me("SoDongTimKiemSanPham") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property ThoiGianTimKiemChamSanPham() As Integer
            Get
                Return CType(Me("ThoiGianTimKiemChamSanPham"),Integer)
            End Get
            Set
                Me("ThoiGianTimKiemChamSanPham") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\PhanMemTMT\Backup")>  _
        Public Property DuongDanFileBackup() As String
            Get
                Return CType(Me("DuongDanFileBackup"),String)
            End Get
            Set
                Me("DuongDanFileBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CoBak10Ngay() As Boolean
            Get
                Return CType(Me("CoBak10Ngay"),Boolean)
            End Get
            Set
                Me("CoBak10Ngay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CoBak30Ngay() As Boolean
            Get
                Return CType(Me("CoBak30Ngay"),Boolean)
            End Get
            Set
                Me("CoBak30Ngay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SaoLuuKhiDangNhap() As Boolean
            Get
                Return CType(Me("SaoLuuKhiDangNhap"),Boolean)
            End Get
            Set
                Me("SaoLuuKhiDangNhap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SaoLuuKhiTatChuongTrinh() As Boolean
            Get
                Return CType(Me("SaoLuuKhiTatChuongTrinh"),Boolean)
            End Get
            Set
                Me("SaoLuuKhiTatChuongTrinh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SaoLuuHangTuan() As Boolean
            Get
                Return CType(Me("SaoLuuHangTuan"),Boolean)
            End Get
            Set
                Me("SaoLuuHangTuan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SaoLuuVaoThuMay() As Integer
            Get
                Return CType(Me("SaoLuuVaoThuMay"),Integer)
            End Get
            Set
                Me("SaoLuuVaoThuMay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property KhongDuocPhepBackup() As Boolean
            Get
                Return CType(Me("KhongDuocPhepBackup"),Boolean)
            End Get
            Set
                Me("KhongDuocPhepBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LuonXacNhanHoaDon() As Boolean
            Get
                Return CType(Me("LuonXacNhanHoaDon"),Boolean)
            End Get
            Set
                Me("LuonXacNhanHoaDon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HienFormSauKhiIn() As Boolean
            Get
                Return CType(Me("HienFormSauKhiIn"),Boolean)
            End Get
            Set
                Me("HienFormSauKhiIn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property DelayTimKiemMaVach() As Integer
            Get
                Return CType(Me("DelayTimKiemMaVach"),Integer)
            End Get
            Set
                Me("DelayTimKiemMaVach") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property KieuPhieuThu() As Integer
            Get
                Return CType(Me("KieuPhieuThu"),Integer)
            End Get
            Set
                Me("KieuPhieuThu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property KieuPhieuChi() As Integer
            Get
                Return CType(Me("KieuPhieuChi"),Integer)
            End Get
            Set
                Me("KieuPhieuChi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TMT")>  _
        Public Property TenCuaHang() As String
            Get
                Return CType(Me("TenCuaHang"),String)
            End Get
            Set
                Me("TenCuaHang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TimKiemTheoMaVach() As Boolean
            Get
                Return CType(Me("TimKiemTheoMaVach"),Boolean)
            End Get
            Set
                Me("TimKiemTheoMaVach") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property KieuTimKiem() As Integer
            Get
                Return CType(Me("KieuTimKiem"),Integer)
            End Get
            Set
                Me("KieuTimKiem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TimKiemTheo() As Integer
            Get
                Return CType(Me("TimKiemTheo"),Integer)
            End Get
            Set
                Me("TimKiemTheo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property KieuDatHang() As Integer
            Get
                Return CType(Me("KieuDatHang"),Integer)
            End Get
            Set
                Me("KieuDatHang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property KieuBaoGia() As Integer
            Get
                Return CType(Me("KieuBaoGia"),Integer)
            End Get
            Set
                Me("KieuBaoGia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property idKhachHangMacDinh() As Integer
            Get
                Return CType(Me("idKhachHangMacDinh"),Integer)
            End Get
            Set
                Me("idKhachHangMacDinh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ChonKhachHangMacDinh() As Boolean
            Get
                Return CType(Me("ChonKhachHangMacDinh"),Boolean)
            End Get
            Set
                Me("ChonKhachHangMacDinh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("zhPaYpvkub6jXXD2Nm7I+w==")>  _
        Public Property TaiKhoan() As String
            Get
                Return CType(Me("TaiKhoan"),String)
            End Get
            Set
                Me("TaiKhoan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("KoJs5PPSPFmBayJoSIVf5Q==")>  _
        Public Property MatKhau() As String
            Get
                Return CType(Me("MatKhau"),String)
            End Get
            Set
                Me("MatKhau") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TuDongKiemTraCapNhat() As Boolean
            Get
                Return CType(Me("TuDongKiemTraCapNhat"),Boolean)
            End Get
            Set
                Me("TuDongKiemTraCapNhat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ZoomReport() As Integer
            Get
                Return CType(Me("ZoomReport"),Integer)
            End Get
            Set
                Me("ZoomReport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("rUcQ4h5+G3vJeYimTQV8Rm0cFEYl9mXOkH95Ly0Efkrq7OlM3KU493OX6WQaXnkFDIfcHVYVWh9iDnqAR"& _ 
            "qsdfvUqsptoAAnww3Mk3NTIo0AmZytNv8ZclKR29w1ztAUUBLQFmGpX2Ma3RDYhxG0M5Jt5zDWEN+iA2"& _ 
            "OqKb5TJdWeJO6vt6cBcUO/DGdFDe9zz")>  _
        Public Property ThongTinKetNoi() As String
            Get
                Return CType(Me("ThongTinKetNoi"),String)
            End Get
            Set
                Me("ThongTinKetNoi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SoLien() As Integer
            Get
                Return CType(Me("SoLien"),Integer)
            End Get
            Set
                Me("SoLien") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property KieuPhieuDoiTra() As Integer
            Get
                Return CType(Me("KieuPhieuDoiTra"),Integer)
            End Get
            Set
                Me("KieuPhieuDoiTra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CongGopSanPham() As Boolean
            Get
                Return CType(Me("CongGopSanPham"),Boolean)
            End Get
            Set
                Me("CongGopSanPham") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HienAnhTrenGiaoDienBanHang() As Boolean
            Get
                Return CType(Me("HienAnhTrenGiaoDienBanHang"),Boolean)
            End Get
            Set
                Me("HienAnhTrenGiaoDienBanHang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9600")>  _
        Public Property BaurateCan() As Integer
            Get
                Return CType(Me("BaurateCan"),Integer)
            End Get
            Set
                Me("BaurateCan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM4")>  _
        Public Property CongCom() As String
            Get
                Return CType(Me("CongCom"),String)
            End Get
            Set
                Me("CongCom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("k")>  _
        Public Property ReadToCan() As String
            Get
                Return CType(Me("ReadToCan"),String)
            End Get
            Set
                Me("ReadToCan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[0-9]*\.[0-9]*")>  _
        Public Property PatermCan() As String
            Get
                Return CType(Me("PatermCan"),String)
            End Get
            Set
                Me("PatermCan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13")>  _
        Public Property KieuHoaDonGTGT() As Integer
            Get
                Return CType(Me("KieuHoaDonGTGT"),Integer)
            End Get
            Set
                Me("KieuHoaDonGTGT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strGhiChu() As String
            Get
                Return CType(Me("strGhiChu"),String)
            End Get
            Set
                Me("strGhiChu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strCongTien() As String
            Get
                Return CType(Me("strCongTien"),String)
            End Get
            Set
                Me("strCongTien") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strChietKhauPhanTram() As String
            Get
                Return CType(Me("strChietKhauPhanTram"),String)
            End Get
            Set
                Me("strChietKhauPhanTram") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strChietKhauGiamTien() As String
            Get
                Return CType(Me("strChietKhauGiamTien"),String)
            End Get
            Set
                Me("strChietKhauGiamTien") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strThanhTien() As String
            Get
                Return CType(Me("strThanhTien"),String)
            End Get
            Set
                Me("strThanhTien") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strTienSauThue() As String
            Get
                Return CType(Me("strTienSauThue"),String)
            End Get
            Set
                Me("strTienSauThue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strTenSanPhamQuaDai() As String
            Get
                Return CType(Me("strTenSanPhamQuaDai"),String)
            End Get
            Set
                Me("strTenSanPhamQuaDai") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HienAnhTrenHoaDon() As Boolean
            Get
                Return CType(Me("HienAnhTrenHoaDon"),Boolean)
            End Get
            Set
                Me("HienAnhTrenHoaDon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CotInMaVach() As Integer
            Get
                Return CType(Me("CotInMaVach"),Integer)
            End Get
            Set
                Me("CotInMaVach") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property LoaiTemCanHang() As Integer
            Get
                Return CType(Me("LoaiTemCanHang"),Integer)
            End Get
            Set
                Me("LoaiTemCanHang") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=QLBanHang_MatTroi;Persist Security Info=True;User I"& _ 
            "D=sa;Password=123123")>  _
        Public ReadOnly Property phongTMT_PhanMemBanHang_MatTroi_DemoConnectionString() As String
            Get
                Return CType(Me("phongTMT_PhanMemBanHang_MatTroi_DemoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property SoSoKhongPhieuThuChi() As Integer
            Get
                Return CType(Me("SoSoKhongPhieuThuChi"),Integer)
            End Get
            Set
                Me("SoSoKhongPhieuThuChi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property SoSoKhongHoaDon() As Integer
            Get
                Return CType(Me("SoSoKhongHoaDon"),Integer)
            End Get
            Set
                Me("SoSoKhongHoaDon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property SoDongKhachHangTrenMotTrang() As Integer
            Get
                Return CType(Me("SoDongKhachHangTrenMotTrang"),Integer)
            End Get
            Set
                Me("SoDongKhachHangTrenMotTrang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property SoSoKhongPhieuXuatNhap() As Integer
            Get
                Return CType(Me("SoSoKhongPhieuXuatNhap"),Integer)
            End Get
            Set
                Me("SoSoKhongPhieuXuatNhap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CÔNG TY TNHH THƯƠNG MẠI & DỊCH VỤ")>  _
        Public Property TenCongTy() As String
            Get
                Return CType(Me("TenCongTy"),String)
            End Get
            Set
                Me("TenCongTy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ThongTinLienHe() As String
            Get
                Return CType(Me("ThongTinLienHe"),String)
            End Get
            Set
                Me("ThongTinLienHe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DiaChi() As String
            Get
                Return CType(Me("DiaChi"),String)
            End Get
            Set
                Me("DiaChi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NhacNho() As String
            Get
                Return CType(Me("NhacNho"),String)
            End Get
            Set
                Me("NhacNho") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("450")>  _
        Public Property ChieuDaiOTienChu() As Integer
            Get
                Return CType(Me("ChieuDaiOTienChu"),Integer)
            End Get
            Set
                Me("ChieuDaiOTienChu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HienDuongGachCuoi() As Boolean
            Get
                Return CType(Me("HienDuongGachCuoi"),Boolean)
            End Get
            Set
                Me("HienDuongGachCuoi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property SoDongToiDa() As Integer
            Get
                Return CType(Me("SoDongToiDa"),Integer)
            End Get
            Set
                Me("SoDongToiDa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property ChieuDaiODiaChi() As Integer
            Get
                Return CType(Me("ChieuDaiODiaChi"),Integer)
            End Get
            Set
                Me("ChieuDaiODiaChi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmailCongTy() As String
            Get
                Return CType(Me("EmailCongTy"),String)
            End Get
            Set
                Me("EmailCongTy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property WebsiteCongTy() As String
            Get
                Return CType(Me("WebsiteCongTy"),String)
            End Get
            Set
                Me("WebsiteCongTy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MaSoThue() As String
            Get
                Return CType(Me("MaSoThue"),String)
            End Get
            Set
                Me("MaSoThue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SoTaiKhoan() As String
            Get
                Return CType(Me("SoTaiKhoan"),String)
            End Get
            Set
                Me("SoTaiKhoan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DienThoai() As String
            Get
                Return CType(Me("DienThoai"),String)
            End Get
            Set
                Me("DienThoai") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Fax() As String
            Get
                Return CType(Me("Fax"),String)
            End Get
            Set
                Me("Fax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.63")>  _
        Public Property KhoangCachHaiDongLienTiep() As Double
            Get
                Return CType(Me("KhoangCachHaiDongLienTiep"),Double)
            End Get
            Set
                Me("KhoangCachHaiDongLienTiep") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("240")>  _
        Public Property ChieuDaiOHangHoa() As Integer
            Get
                Return CType(Me("ChieuDaiOHangHoa"),Integer)
            End Get
            Set
                Me("ChieuDaiOHangHoa") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://iclickupdater.hayketnoi.com/UpdateIClick.svc")>  _
        Public ReadOnly Property PhanMemBanHang_com_hayketnoi_iclickupdater_UpdateIClick() As String
            Get
                Return CType(Me("PhanMemBanHang_com_hayketnoi_iclickupdater_UpdateIClick"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\")>  _
        Public Property DuongDanLuuExcel() As String
            Get
                Return CType(Me("DuongDanLuuExcel"),String)
            End Get
            Set
                Me("DuongDanLuuExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SoLienIn() As Integer
            Get
                Return CType(Me("SoLienIn"),Integer)
            End Get
            Set
                Me("SoLienIn") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=QLBanHang_MatTroi;Persist Security Info=True;User I"& _ 
            "D=sa")>  _
        Public ReadOnly Property QLBanHang_MatTroiConnectionString() As String
            Get
                Return CType(Me("QLBanHang_MatTroiConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=tx.skyit.vn;Initial Catalog=phongTMT_PhanMemBanHang_TheSun;User ID=le"& _ 
            "vandong;Password=1q2w3e4r")>  _
        Public ReadOnly Property phongTMT_PhanMemBanHang_TheSunConnectionString() As String
            Get
                Return CType(Me("phongTMT_PhanMemBanHang_TheSunConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PhanMemBanHang.My.MySettings
            Get
                Return Global.PhanMemBanHang.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
